apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{  .Release.Name }}
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replica.count }}
  selector:
    matchLabels:
      app: {{  .Release.Name }}
  template:
    metadata:
      labels:
        app: {{  .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-env-config
        {{- include "charter.resources" . | nindent 8 }}
        livenessProbe:
          {{- toYaml .Values.deployment.probes.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.deployment.probes.readinessProbe | nindent 12 }}
